// ==WindhawkMod==
// @id              matheussma-theme
// @name            MatheusSMA theme
// @description     Taskbar styling and a macOS-style dock hover animation, with magnified icons that are not cut off
// @version         1.0.0
// @author          MatheusSMA
// @github          https://github.com/MatheusSMA
// @include         explorer.exe
// @architecture    x86-64
// @compilerOptions -lcomctl32 -lgdi32 -lole32 -loleaut32 -lruntimeobject -lshcore -lshlwapi -lwindowsapp -luser32
// ==/WindhawkMod==

// Source code is published under The GNU General Public License v3.0.
//
// This mod combines two existing Windhawk mods:
//
//   Windows 11 Taskbar Styler, by m417z - GPLv3
//   https://github.com/m417z/my-windhawk-mods
//
//   Taskbar Dock Animation, by Ph0en1x-dev - MIT
//   https://github.com/ramensoftware/windhawk-mods
//
// See NOTICE.md in the repository for full attribution.
//
// Generated by scripts/build-mod.py from the pinned sources in upstream/.
// Edit parts/ and rebuild rather than editing this file directly.

// ==WindhawkModReadme==
/*
# MatheusSMA theme

Taskbar styling and a macOS-style dock hover animation in one mod, with the
magnified icons actually escaping the taskbar instead of being clipped by it.

Built from **Windows 11 Taskbar Styler** by
[m417z](https://github.com/m417z) and **Taskbar Dock Animation** by
[Ph0en1x-dev](https://github.com/Ph0en1x-dev).

## Why one mod

Run side by side, the two cannot coordinate. Both write to the same XAML
elements: the styler sets geometry and can set `RenderTransform`, while the
animation owns `RenderTransform` on the icons it scales and reads their geometry
every frame.

**Icons no longer get cut off.** The taskbar window is 48 DIP tall and XAML is
not composited outside its host window, so an icon magnified to 180% has nowhere
to go. No amount of resizing elements or opening their clips helps, because all
of it happens inside a window that is still 48 DIP. The fix needs two halves at
once: the window is made taller, and the visible content is pinned back to a
short strip at its bottom so the buttons do not grow along with it. Neither half
works alone, and neither upstream mod can do both.

## Not done yet

**Silent animation loss.** The animation expects a `TransformGroup` with exactly
four children on each element it animates and quietly gives up on anything else,
so a style rule setting `RenderTransform` on a taskbar button stops that icon
animating with no error anywhere. Being one mod makes a guard possible; it is not
written yet.

**Per-frame layout polling.** The animation still hashes the icon host's children
on every rendered frame to notice that the styling changed the layout, instead of
being told directly.

## Installing

This mod replaces both originals. **Uninstall `windows-11-taskbar-styler` and
`taskbar-dock-animation`** after installing it - running all three duplicates the
symbol hooks, and both styling engines compete for the single XAML diagnostics
consumer slot.

## Notes

Two themes are included, `FrostyGlass` and `LiquidGlass2`. The rest of the
upstream styler's themes are not bundled; see `scripts/add-theme.py` in the
repository to pull one in.

Taskbar height reserves screen space even where the strip above the bar is
transparent, so maximized windows stop below the top of the window rather than
the top of the visible bar.
*/
// ==/WindhawkModReadme==

// ==WindhawkModSettings==
/*
- theme: FrostyGlass
  $name: Style - theme
  $description: >-
    Set to None to turn the styling off without uninstalling, which is the first
    step when tracking down a conflict between the styling and the animation.
  $options:
  - "": None
// @@THEME_OPTIONS@@

- frameHeight: 96
  $name: Clipping - taskbar window height (DIP)
  $description: >-
    Height of the taskbar window itself. The stock height is 48, and the window
    has to be at least the magnified height of a button for icons not to be cut
    off: at 180% with a 48 DIP button, that is 86. The area above the visible bar
    is transparent.

- styleConstants: [""]
  $name: Style - constants
  $description: >-
    Theme customization, such as colors. Refer to the theme's page for the
    constants it supports.

- controlStyles:
  - - target: ""
      $name: Target
    - styles: [""]
      $name: Styles
  $name: Style - control styles
  $description: >-
    Extra style rules, applied on top of the theme. This is the way to adjust the
    look without rebuilding the mod.

- themeResourceVariables: [""]
  $name: Style - resource variables
  $description: >-
    Use "Key=Value" to override an existing resource with a new value.

    Use "Key@Dark=Value" or "Key@Light=Value" to define theme-aware resources
    that can be referenced with {ThemeResource Key} in styles.

- clickThroughTaskbar: true
  $name: Style - click-through taskbar
  $description: >-
    Make the empty parts of the taskbar click-through. Only the area with the
    taskbar buttons and the system tray stays clickable.

    On by default here, unlike upstream: this mod always makes the window taller
    than the visible bar, so there is always a transparent strip above it. With
    this off, that strip swallows clicks and hover meant for whatever is behind
    it.

- xamlDiagnosticsHandling: alert
  $name: Style - XAML diagnostics consumer handling
  $description: >-
    How to handle other programs that try to use XAML diagnostics. There can only
    be one consumer at a time. Block will prevent other programs from using it,
    which might break them. Allow will let them use it, which might break this
    mod.
  $options:
  - alert: Alert (prompt before blocking)
  - block: Block other consumers
  - allow: Allow other consumers

// @@DOCK_SETTINGS@@
*/
// ==/WindhawkModSettings==

#include <commctrl.h>
#include <xamlom.h>

#include <atomic>
#include <vector>

#undef GetCurrentTime

#include <winrt/Windows.UI.Xaml.h>
